name: CI

on:
  push:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv with version 0.7.x
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.x"
          enable-cache: true
      
      - name: Lint
        run: uv run make lint
      
      - name: Test
        run: uv run make tests